<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Invoices.Core\Invoices.Core.csproj" />
    <ProjectReference Include="..\Invoices.Rendering\Invoices.Rendering.csproj" />
    <ProjectReference Include="..\Invoices.Integration\Invoices.Integration.csproj" />
    <ProjectReference Include="..\Invoices.Integration.Square\Invoices.Integration.Square.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="SquareConfiguration.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
